name: Deploy
on:
 push:
   branches:
     - prod
jobs:
 deploy:
   runs-on: ubuntu-latest
   steps:
     - name: SSH Deploy
       uses: appleboy/ssh-action@v1
       with:
         host: 72.62.231.124 
         username: admin
         password: Globify2026?
         script: |
           cd /home/globify
           ./deploy.sh